import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Noto_Sans } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans({ subsets: ["latin"] });

// const noto = Noto_Sans({
//   variable: '--font-noto',
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
